// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajtdmenflndkxhvvuwak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdGRtZW5mbG5ka3hodnZ1d2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDU4NDksImV4cCI6MjA3MzEyMTg0OX0.yzsAPbd3XRA5V_DOQ8_Lo0uoVk9_3PCap-bZr1XDlqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});